// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roteiro.Data.EF.Context;

namespace Roteiro.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200421225858_cadastro")]
    partial class cadastro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Roteiro.Data.EF.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<string>("CpfCnpj");

                    b.Property<DateTime?>("DAlteracao");

                    b.Property<DateTime?>("DNasc");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<string>("Email");

                    b.Property<int?>("ICadAlt");

                    b.Property<int?>("IInteresse");

                    b.Property<short?>("Idade");

                    b.Property<int?>("NRua");

                    b.Property<string>("NTelefone");

                    b.Property<string>("Nome");

                    b.Property<int?>("Pais");

                    b.Property<string>("Rua");

                    b.Property<string>("Sexo");

                    b.Property<string>("Uf");

                    b.Property<int?>("XClasse");

                    b.HasKey("Id");

                    b.ToTable("Cadastro");
                });
#pragma warning restore 612, 618
        }
    }
}
